In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("interactive_data.csv")
data

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7
...,...,...,...,...,...,...,...,...
535,536,Unknown,Male,5,White,0,0,NaN
536,537,Unknown,Male,5,Black,0,0,NaN
537,538,Unknown,Male,5,Hispanic,0,0,NaN
538,539,Unknown,Male,5,Asian/Pacific Islander,0,0,NaN
539,540,Unknown,Male,5,Other,0,0,NaN

In [20]:
data.columns

Index(['Unnamed: 0', 'Intent', 'Gender', 'Age', 'Race', 'Deaths', 'Population',
       'Rate'],
      dtype='object')

In [11]:
np.unique(data["Intent"].to_numpy())

array(['Accident', 'Homicide', 'None selected', 'Suicide', 'Unknown'],
      dtype=object)

In [121]:
total_gun_deaths = data[
    (data["Intent"]=="None selected")
    & (data["Gender"]=="None selected") 
    & (data["Age"]=="None selected")
    & (data["Race"]=="None selected")]["Deaths"].iloc[0]

suicide_deaths = data[(data["Intent"]=="Suicide")
        & (data["Gender"]=="None selected") 
        & (data["Age"]=="None selected")
        & (data["Race"]=="None selected")]["Deaths"].iloc[0]

suicide_deaths_proportion = int(100*suicide_deaths/total_gun_deaths)
print(f"The proportion of suicide deaths among all gun deaths is {suicide_deaths_proportion}%")

The proportion of suicide deaths among all gun deaths is 62%

In [117]:
suicide_data = data.loc[data["Intent"]=="Suicide"]
male_suicide = suicide_data.loc[suicide_data["Gender"]=="Male"]

male_suicide_deaths = male_suicide.loc[(male_suicide["Age"]=="None selected")
    & (male_suicide["Race"]=="None selected")]["Deaths"].iloc[0]
male_suicide_proportion = int(100*male_suicide_deaths/suicide_deaths)
print(f"The proportion of male persons among all suicide deathss is {male_suicide_proportion}%")

The proportion of male persons among all suicide deathss is 86%

In [93]:
data

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7
...,...,...,...,...,...,...,...,...
535,536,Unknown,Male,5,White,0,0,NaN
536,537,Unknown,Male,5,Black,0,0,NaN
537,538,Unknown,Male,5,Hispanic,0,0,NaN
538,539,Unknown,Male,5,Asian/Pacific Islander,0,0,NaN
539,540,Unknown,Male,5,Other,0,0,NaN

In [95]:
homicide_deaths = data.loc[(data["Intent"]=="Homicide")
    & (data["Gender"]=="None selected")
    & (data["Age"]=="None selected")
    & (data["Race"]=="None selected")]["Deaths"].iloc[0]
homicide_proportion = int(100*homicide_deaths/total_gun_deaths)
print(f"The proportion of homicides among all gun deathss is {homicide_proportion}%")

The proportion of homicides among all gun deathss is 34%

In [104]:
the_fourth_variable_total = data.loc[(data["Intent"]=="Homicide")
    & (data["Gender"]=="Male")
    & (data["Age"]=="15 - 34")
    & (data["Race"]=="None selected")]["Deaths"].iloc[0]

the_fourth_variable_black = data.loc[(data["Intent"]=="Homicide")
    & (data["Gender"]=="Male")
    & (data["Age"]=="15 - 34")
    & (data["Race"]=="Black")]["Deaths"].iloc[0]

the_fourth_proportion = int(100*the_fourth_variable_black/the_fourth_variable_total)

print(f"{the_fourth_proportion}% of homicide victims who are males in the age-group of 15--34 are black")

66% of homicide victims who are males in the age-group of 15--34 are black

In [113]:
woman_homicide = data.loc[(data["Intent"]=="Homicide")
    & (data["Gender"]=="Female")
    & (data["Race"]=="None selected")
    & (data["Age"]=="None selected")]["Deaths"].iloc[0]

woman_homicide_proportion = int(100*woman_homicide/homicide_deaths)

print(f"Women constitue only {woman_homicide_proportion}% of the total homicide victims")

Women constitue only 15% of the total homicide victims